name: Onboarding
version: '${version}'
main: org.modernbeta.onboarding.Onboarding
api-version: '1.20'
folia-supported: true
depend:
  - SuperVanish
  - Essentials
commands:
  accept:
    description: Accepts the rules for an onboarding player
    usage: /accept
    aliases:
      - agree
      - yes
  deny:
    description: Denies the rules and kicks the player from the server
    usage: /deny
    aliases:
      - disagree
      - no